### PR TITLE
Stop making HTTP requests in tests

### PR DESCRIPTION
**Pull request by mangin**
Hi someone,
Some tests ignore session, so betamax can't mock requests  for these tests. And these tests go to the Internet.

P.S. On my work, we don't allow any test to go to the Internet. So these tests are failed in our environment.

### CODE REVIEW

**Comment by FelixSchwarz** [comment]
Thank you very much for your patch. Actually the test suite currently fails as two URLs return a 404 and thus breaking the tests. Your patch preserved the resources and ensures the test suite passes again.

Please merge :-)

**Comment by mangin** [comment]
Hi FelixSchwarz..
I can't do it because I'm not an owner. I'm waiting for a merge 1 year...

I see :
All checks have passed
1 successful check
This branch has no conflicts with the base branch
Only those with write access to this repository can merge pull requests.

**Comment by mangin** [comment]
I've sent an email to owner... I hope he will reply soon

**Review by jdufresne — APPROVED** [review]

**Comment by kloczek** [comment]
This PR no longer applies on top of 0.10.1.

**Comment by pquentin** [comment]
I think it does apply? Otherwise GitHub would have complained. I do plan to merge this soon.

**Pull request merged**
