### PR TITLE
Add pyopenssl to install_requires

### PR DESCRIPTION
**Pull request by altendky**
https://github.com/requests/toolbelt/commit/675fab790b0e9fefd6beb0f38d9a5da4b056c59c
https://github.com/requests/toolbelt/issues/241

### CODE REVIEW

**Comment by jeid64** [comment]
https://github.com/requests/toolbelt/commit/675fab790b0e9fefd6beb0f38d9a5da4b056c59c
Wasn't caught in testing because the tox configuration installs it.

**Comment by altendky** [comment]
@jeid64 good point.  Let's see if it works without those.

**Comment by sigmavirus24** [comment]
Can we instead just try except around the import that's offending and ignore it. I think the adapter should be resilient to not having the pyopenssl backend. That would be better than blanket requiring pyopenssl here.

**Comment by ryanwilsonperkin** [comment]
@sigmavirus24 there does appear to be a try/except around it, but not working properly. Perhaps the condition that's checking the requests version is incorrect?

https://github.com/requests/toolbelt/blob/da420bdfd9f8baf2041ee2cf1a666e1fc59b1551/requests_toolbelt/_compat.py#L52-L59

**Comment by sigmavirus24** [comment]
No, I believe the unconditional import from `*urllib3.contrib.pyopenssl` whether vendored or not is the problem here and I missed that during review.

**Comment by ryanwilsonperkin** [comment]
@sigmavirus24 gotcha. How about this? https://github.com/requests/toolbelt/pull/243

**Comment by sigmavirus24** [comment]
Superseded by #243

**Comment by sigmavirus24** [comment]
Thanks for sending this @altendky

**Pull request closed without merging**
