### PR TITLE
Update _compat.py

### PR DESCRIPTION
**Pull request by chickiyeah**
Mapping Error

### CODE REVIEW

**Comment by sigmavirus24** [comment]
What error is this supposed to be fixing?

**Comment by sigmavirus24** [comment]
Line 48 has this exact import so I'm still confused by what you're trying to fix here

**Comment by chickiyeah** [comment]
> Line 48 has this exact import so I'm still confused by what you're trying to fix here

I corrected it because my server couldn't read the line at 18 when I was running on my server and there was an error in the operation

**Comment by chickiyeah** [comment]
You may also consider moving up the try phrase in line 48.

**Comment by sigmavirus24** [comment]
If it was line 18, then what you've done here won't help, nor will moving the line where this happens.

There's almost no information in this about the versions you're using, the stack trace or anything really that could possibly help us help you.

**Pull request closed without merging**
